"""
build.py — Bundle src/ modules into a single solution.py for submission.

Usage:
    python build.py

The output file (solution.py) is self-contained:
  - Starts with the required `from datamodel import ...` line.
  - Contains all strategy code inlined in dependency order.
  - Strips all intra-package imports (`from src.*`, `import src.*`).
  - Strips `from __future__ import annotations` (merged into one at top).
  - Strips per-file duplicate `import json` / `import math` etc.
    (kept once at the top of the output).
"""

import re
from pathlib import Path

# ── Dependency order: config → base → products → trader ─────────────────────
SRC_FILES: list[str] = [
    "src/config.py",
    "src/base.py",
    "src/strategies/pair_trading.py",
    "src/strategies/seasonal.py",
    "src/products/emeralds.py",
    "src/products/tomatoes.py",
    "src/trader.py",
]

OUTPUT_FILE = "solution.py"

# Lines / patterns to strip from individual modules during bundling
STRIP_PATTERNS: list[re.Pattern] = [
    re.compile(r"^from __future__ import annotations"),
    re.compile(r"^from datamodel import"),
    re.compile(r"^from src\b"),
    re.compile(r"^import src\b"),
]

# Standard-library imports to hoist (deduplicated) to the top
STDLIB_IMPORT_RE = re.compile(r"^(import\s+\w[\w.]*|from\s+\w[\w.]*\s+import\s+.+)$")
DATAMODEL_IMPORTS = (
    "from datamodel import ("
    "\n    ConversionObservation, Listing, Observation, Order, OrderDepth,"
    "\n    ProsperityEncoder, Product, Symbol, Trade, TradingState,"
    "\n)"
)

HEADER = f"""\
# =============================================================================
# solution.py — Auto-generated by build.py. DO NOT EDIT DIRECTLY.
# =============================================================================
from __future__ import annotations
{DATAMODEL_IMPORTS}
"""


def strip_line(line: str) -> bool:
    stripped = line.strip()
    for pat in STRIP_PATTERNS:
        if pat.match(stripped):
            return True
    return False


def build() -> None:
    hoisted_imports: list[str] = []
    seen_imports: set[str] = set()
    body_sections: list[str] = []

    for filepath in SRC_FILES:
        path = Path(filepath)
        if not path.exists():
            print(f"WARNING: {filepath} not found — skipping.")
            continue

        lines = path.read_text(encoding="utf-8").splitlines()
        body_lines: list[str] = []

        for line in lines:
            stripped = line.strip()

            # Drop lines handled by the global header
            if strip_line(line):
                continue

            # Hoist stdlib/third-party imports (always remove from body; hoist once)
            if STDLIB_IMPORT_RE.match(stripped):
                if stripped not in seen_imports:
                    hoisted_imports.append(line)
                    seen_imports.add(stripped)
                continue  # Always skip from body regardless of dedup

            body_lines.append(line)

        # Trim leading/trailing blank lines from the body section
        while body_lines and not body_lines[0].strip():
            body_lines.pop(0)
        while body_lines and not body_lines[-1].strip():
            body_lines.pop()

        if body_lines:
            section_header = f"# {'─' * 72}\n# {filepath}\n# {'─' * 72}"
            body_sections.append(section_header + "\n" + "\n".join(body_lines))

    output_parts = [HEADER]
    if hoisted_imports:
        output_parts.append("\n".join(hoisted_imports))
    output_parts.append("\n\n")
    output_parts.append("\n\n".join(body_sections))
    output_parts.append("\n")

    Path(OUTPUT_FILE).write_text("\n".join(output_parts), encoding="utf-8")
    print(f"Built {OUTPUT_FILE} successfully ({Path(OUTPUT_FILE).stat().st_size:,} bytes).")


if __name__ == "__main__":
    build()
