# =============================================================================
# IMC PROSPERITY 4 — ROUND 2 SUBMISSION
# Backtest result: 8,899.53 (single day)
#   - INTARIAN_PEPPER_ROOT: 7,307.00  (deterministic trend ceiling)
#   - ASH_COATED_OSMIUM:    1,592.53  (MM at bot walls, 65/35 tier split)
# Submission ID: 291130
# Date: 2026-04-18
# Source: built from src/products/{ash_coated_osmium,intarian_pepper_root}.py
#         via build.py. Do not edit this file directly — edit src/ and rebuild.
# =============================================================================
from __future__ import annotations
from datamodel import (
    ConversionObservation, Listing, Observation, Order, OrderDepth,
    ProsperityEncoder, Product, Symbol, Trade, TradingState,
)

from collections import deque
import json



# ────────────────────────────────────────────────────────────────────────
# src/config.py
# ────────────────────────────────────────────────────────────────────────
# ============================================================
# GLOBAL CONFIG
# ============================================================

DEBUG = False  # NEVER set True in competition submissions — causes Lambda timeouts

# Position limits per product (updated each round)
LIMITS: dict[str, int] = {
    "EMERALDS": 80,
    "TOMATOES": 80,
    # Round 2 — ASH_COATED_OSMIUM hard limit confirmed = 80
    "ASH_COATED_OSMIUM": 80,
    # Round 2 — bot offers 25/tick; limit 80 fills over 3-4 ticks for max trend capture
    # (9910 strategy used 80 and got ~7320 IPR PnL; 75 → 6836; 25 → 2247)
    "INTARIAN_PEPPER_ROOT": 80,
}

# Master switch: "aggressive" = wide market making, take spreads freely
#                "conservative" = only take near-certain arb, tight sizing
# Can be overridden per-product based on realised volatility regime.
MASTER_SWITCH: str = "aggressive"

# ────────────────────────────────────────────────────────────────────────
# src/base.py
# ────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────────
# Rolling statistics — pure Python, no pandas dependency
# ──────────────────────────────────────────────────────────────────────────────

class RollingWindow:
    """
    Fixed-length rolling window with O(1) append and O(n) mean/std.

    Used for z-score-based pair trading and basket arbitrage.
    State is serialised as a plain list so it can be stored in traderData JSON.

    Lesson from nicolassinott: they used pandas Series with a 200-period window
    and a 5-period short-term smoother. We replicate this in pure Python.
    """

    def __init__(self, maxlen: int) -> None:
        self._maxlen = maxlen
        self._data: deque[float] = deque(maxlen=maxlen)

    # ── Serialisation ──────────────────────────────────────────────────────

    def to_list(self) -> list[float]:
        return list(self._data)

    @classmethod
    def from_list(cls, data: list[float], maxlen: int) -> "RollingWindow":
        w = cls(maxlen)
        w._data = deque(data[-maxlen:], maxlen=maxlen)
        return w

    # ── Mutations ──────────────────────────────────────────────────────────

    def push(self, value: float) -> None:
        self._data.append(value)

    # ── Queries ────────────────────────────────────────────────────────────

    def __len__(self) -> int:
        return len(self._data)

    def is_ready(self) -> bool:
        return len(self._data) == self._maxlen

    def mean(self) -> float:
        n = len(self._data)
        if n == 0:
            return 0.0
        return sum(self._data) / n

    def short_mean(self, n: int = 5) -> float:
        """Mean of the most recent n values (short-term smoother, like nicolassinott's spread_5)."""
        tail = list(self._data)[-n:]
        if not tail:
            return 0.0
        return sum(tail) / len(tail)

    def std(self) -> float:
        n = len(self._data)
        if n < 2:
            return 0.0
        m = self.mean()
        return (sum((x - m) ** 2 for x in self._data) / (n - 1)) ** 0.5

    def zscore(self, short_n: int = 5) -> float | None:
        """
        Z-score of the short-term mean relative to the long-term mean/std.
        Returns None until the window is populated.
        """
        if len(self._data) < max(short_n + 1, 20):
            return None
        s = self.std()
        if s == 0.0:
            return None
        return (self.short_mean(short_n) - self.mean()) / s


# ──────────────────────────────────────────────────────────────────────────────
# Base product trader
# ──────────────────────────────────────────────────────────────────────────────

class BaseProductTrader:
    """
    Shared utilities for all per-product traders.

    Interface:
      run(state, td) -> list[Order]
        state : current TradingState
        td    : already-parsed traderData dict (read + write; changes are
                persisted by Trader.run() after all sub-traders finish)

    Quantities: positive = buy, negative = sell.
    """

    def __init__(self, symbol: str, limit: int) -> None:
        self.symbol = symbol
        self.limit = limit
        self._orders: list[Order] = []

    # ── Internal helpers ───────────────────────────────────────────────────

    def _reset(self) -> None:
        self._orders = []

    def _buy(self, price: int, qty: int) -> None:
        if qty > 0:
            self._orders.append(Order(self.symbol, int(price), int(qty)))

    def _sell(self, price: int, qty: int) -> None:
        if qty > 0:
            self._orders.append(Order(self.symbol, int(price), -int(qty)))

    # ── Position helpers ───────────────────────────────────────────────────

    def pos(self, state: TradingState) -> int:
        return state.position.get(self.symbol, 0)

    def buy_capacity(self, state: TradingState) -> int:
        return self.limit - self.pos(state)

    def sell_capacity(self, state: TradingState) -> int:
        return self.limit + self.pos(state)

    # ── Order-book helpers ─────────────────────────────────────────────────

    @staticmethod
    def best_bid(depth: OrderDepth) -> int | None:
        return max(depth.buy_orders) if depth.buy_orders else None

    @staticmethod
    def best_ask(depth: OrderDepth) -> int | None:
        return min(depth.sell_orders) if depth.sell_orders else None

    @staticmethod
    def bid_volume(depth: OrderDepth, price: int) -> int:
        return depth.buy_orders.get(price, 0)

    @staticmethod
    def ask_volume(depth: OrderDepth, price: int) -> int:
        return abs(depth.sell_orders.get(price, 0))

    @staticmethod
    def vwap_mid(depth: OrderDepth) -> float | None:
        """Volume-weighted mid using best bid and best ask."""
        bb = max(depth.buy_orders) if depth.buy_orders else None
        ba = min(depth.sell_orders) if depth.sell_orders else None
        if bb is None or ba is None:
            return float(bb or ba or 0) or None
        bv = depth.buy_orders[bb]
        av = abs(depth.sell_orders[ba])
        total = bv + av
        if total == 0:
            return (bb + ba) / 2.0
        return (bb * av + ba * bv) / total

    @staticmethod
    def mid(depth: OrderDepth) -> float | None:
        bb = max(depth.buy_orders) if depth.buy_orders else None
        ba = min(depth.sell_orders) if depth.sell_orders else None
        if bb is not None and ba is not None:
            return (bb + ba) / 2.0
        return float(bb or ba or 0) or None

    # ── Insider signal helpers ─────────────────────────────────────────────

    # Key insight from both Alpha Animals and Frankfurt Hedgehogs (P3 winners):
    # a named bot "Olivia" consistently traded at daily extremes, providing a
    # direction signal. We track any known insider name rather than hard-coding
    # one, so the framework generalises to new rounds.
    INSIDER_NAMES: frozenset[str] = frozenset({"Olivia", "Caesar", "Vladimir", "Camilla"})

    @classmethod
    def insider_direction(cls, state: TradingState, symbol: str) -> int:
        """
        +1 if an insider net-bought this tick, -1 if net-sold, 0 otherwise.
        """
        trades = state.market_trades.get(symbol, [])
        bought = sum(t.quantity for t in trades if t.buyer in cls.INSIDER_NAMES)
        sold = sum(t.quantity for t in trades if t.seller in cls.INSIDER_NAMES)
        if bought > sold:
            return 1
        if sold > bought:
            return -1
        return 0

    # ── Wash-trade guard ───────────────────────────────────────────────────

    def _no_wash_trades(self, orders: list[Order]) -> list[Order]:
        """
        Remove any buy order whose price ≥ a sell order's price in the same
        list. Such pairs would self-fill ('wash trade') — disqualifying under
        IMC rules.
        """
        buys = [(i, o) for i, o in enumerate(orders) if o.quantity > 0]
        sells = [(i, o) for i, o in enumerate(orders) if o.quantity < 0]
        bad_indices: set[int] = set()
        for bi, bo in buys:
            for si, so in sells:
                if bo.price >= so.price:
                    bad_indices.add(bi)
                    bad_indices.add(si)
        return [o for i, o in enumerate(orders) if i not in bad_indices]

    # ── Main interface ─────────────────────────────────────────────────────

    def run(self, state: TradingState, td: dict) -> list[Order]:
        raise NotImplementedError

# ────────────────────────────────────────────────────────────────────────
# src/products/ash_coated_osmium.py
# ────────────────────────────────────────────────────────────────────────
class AshCoatedOsmiumTrader(BaseProductTrader):
    """
    Market maker for ASH_COATED_OSMIUM — fixed fair-value product.

    Data observations (confirmed from backtests):
      - Fair value ~10 000; dynamic FV = (dom_bid + dom_ask) // 2.
      - Bot walls at FV ± 8. Position limit: 80.
      - MAX_SPREAD=8: keeps both passive tiers distinct (MAX_SPREAD<8
        collapses secondary into primary → −380 ticks in 280528).

    Two-level passive quoting:
      - Primary (65%): just inside dominant bid/ask.
      - Secondary (35%): at the bot wall cap (FV ± MAX_SPREAD).
      - 0.80 tested (290888, −510 ticks): overweights inside → saturates
        fast, 20% on outer tier misses wall fills that cycle inventory.
    """

    FAIR_VALUE:   int   = 10_000
    MAX_SPREAD:   int   = 8      # bot wall at FV ± 8; keeps two quote tiers distinct
    PRIMARY_FRAC: float = 0.65
    FV_MAX_DRIFT: int   = 20     # sanity cap: dynamic FV won't deviate > 20 from FAIR_VALUE

    # Three-tier inventory skew thresholds (fraction of limit)
    MED_TIER:  float = 0.30
    HIGH_TIER: float = 0.65
    # Note: FV mean-reversion skew tested (280961, 281055) and rejected.
    # Signal is real (avg next-tick delta up to ±1.28), but MM already
    # exploits reversion structurally via passive fills. Adding a quote
    # skew shifts our quote onto/near the bot wall, costing fill rate.

    def _dominant_bid(self, depth) -> int | None:
        """Highest bid with vol >= 5 — bot wall proxy."""
        candidates = [p for p, v in depth.buy_orders.items() if v >= 5]
        return max(candidates) if candidates else self.best_bid(depth)

    def _dominant_ask(self, depth) -> int | None:
        """Lowest ask with vol >= 5 — bot wall proxy."""
        candidates = [p for p, v in depth.sell_orders.items() if abs(v) >= 5]
        return min(candidates) if candidates else self.best_ask(depth)

    def _effective_fv(self, dom_bid, dom_ask) -> int:
        """
        Compute effective FV from dominant bid/ask midpoint.
        Falls back to FAIR_VALUE when one or both sides are missing or
        the implied mid drifts too far from the static anchor.
        """
        if dom_bid is not None and dom_ask is not None:
            implied = (dom_bid + dom_ask) // 2
            if abs(implied - self.FAIR_VALUE) <= self.FV_MAX_DRIFT:
                return implied
        return self.FAIR_VALUE

    def run(self, state: TradingState, td: dict) -> list[Order]:
        self._reset()
        depth = state.order_depths.get(self.symbol)
        if not depth:
            return []

        pos = self.pos(state)
        buy_cap = self.buy_capacity(state)
        sell_cap = self.sell_capacity(state)
        insider = self.insider_direction(state, self.symbol)

        # -- 1. Dynamic FV (persisted across ticks) ----------------------
        dom_bid = self._dominant_bid(depth)
        dom_ask = self._dominant_ask(depth)
        fv = self._effective_fv(dom_bid, dom_ask)

        # -- 2. Aggressive takes -----------------------------------------
        for ask in sorted(depth.sell_orders):
            if buy_cap <= 0:
                break
            if ask < fv:
                vol = min(self.ask_volume(depth, ask), buy_cap)
                self._buy(ask, vol)
                buy_cap -= vol
            elif ask == fv and (pos < 0 or insider > 0):
                vol = min(self.ask_volume(depth, ask), buy_cap)
                self._buy(ask, vol)
                buy_cap -= vol

        for bid in sorted(depth.buy_orders, reverse=True):
            if sell_cap <= 0:
                break
            if bid > fv:
                vol = min(self.bid_volume(depth, bid), sell_cap)
                self._sell(bid, vol)
                sell_cap -= vol
            elif bid == fv and (pos > 0 or insider < 0):
                vol = min(self.bid_volume(depth, bid), sell_cap)
                self._sell(bid, vol)
                sell_cap -= vol

        # -- 3. Three-tier inventory skew --------------------------------
        inv_ratio = abs(pos) / self.limit
        if inv_ratio <= self.MED_TIER:
            skew = 0
        elif inv_ratio <= self.HIGH_TIER:
            skew = 1 if pos > 0 else -1
        else:
            skew = 2 if pos > 0 else -2

        # -- 4. Passive quotes just inside bot wall ----------------------
        raw_bid = (dom_bid + 1) if (dom_bid is not None and dom_bid < fv) else (fv - 1)
        primary_bid = max(fv - self.MAX_SPREAD, min(fv - 1, raw_bid)) - skew

        raw_ask = (dom_ask - 1) if (dom_ask is not None and dom_ask > fv) else (fv + 1)
        primary_ask = min(fv + self.MAX_SPREAD, max(fv + 1, raw_ask)) - skew

        # Secondary: anchor to bot wall (dom_bid/dom_ask) so tiers stay
        # distinct even when FV drifts (fix for 280528 collapse bug).
        if dom_bid is not None and dom_bid < primary_bid:
            secondary_bid = dom_bid
        else:
            secondary_bid = primary_bid - 2

        if dom_ask is not None and dom_ask > primary_ask:
            secondary_ask = dom_ask
        else:
            secondary_ask = primary_ask + 2

        # Primary clipped inside ±MAX_SPREAD of the drifted FV.
        primary_bid = max(fv - self.MAX_SPREAD, min(fv - 1, primary_bid))
        primary_ask = min(fv + self.MAX_SPREAD, max(fv + 1, primary_ask))
        # Secondary only needs to be strictly distinct from primary; the
        # bot wall (dom_bid/dom_ask) is itself a natural outer bound, so
        # no fv-anchored clip (that was the 280528 collapse cause).
        secondary_bid = min(primary_bid - 1, secondary_bid)
        secondary_ask = max(primary_ask + 1, secondary_ask)

        if buy_cap > 0:
            prim_qty = max(1, round(buy_cap * self.PRIMARY_FRAC))
            sec_qty  = buy_cap - prim_qty
            self._buy(primary_bid, prim_qty)
            if sec_qty > 0:
                self._buy(secondary_bid, sec_qty)

        if sell_cap > 0:
            prim_qty = max(1, round(sell_cap * self.PRIMARY_FRAC))
            sec_qty  = sell_cap - prim_qty
            self._sell(primary_ask, prim_qty)
            if sec_qty > 0:
                self._sell(secondary_ask, sec_qty)

        orders = self._no_wash_trades(self._orders)

        if DEBUG:
            print(
                f"[ASH_COATED_OSMIUM] pos={pos} fv={fv} skew={skew} insider={insider} "
                f"dom={dom_bid}/{dom_ask} "
                f"bid={primary_bid}/{secondary_bid} ask={primary_ask}/{secondary_ask}"
            )

        return orders

# ────────────────────────────────────────────────────────────────────────
# src/products/intarian_pepper_root.py
# ────────────────────────────────────────────────────────────────────────
class IntarianPepperRootTrader(BaseProductTrader):
    """
    Trend follower for INTARIAN_PEPPER_ROOT.

    Data observations (Round 2, 3 days):
      - Price rises at exactly +1.0 per 1000 timestamps, perfectly linear.
      - Day -1: 11001 -> 12000, Day 0: 12000 -> 13000, Day 1: 13000 -> 14000.
      - Residual std ~2.7 ticks, max ±12 — near-zero noise.
      - Bot offers ~25 units per tick; platform limit = 80.
        Accumulate over 3-4 ticks to reach max position.

    Strategy:
      - Hold maximum long (80 units) at all times.
      - Never sell — price is monotonically rising.
      - Expected PnL: 80 × 100 trend ticks/backtest day ≈ 7,320 net (9910 baseline).

    Execution:
      1. Take all available asks aggressively (trend gain >> half-spread cost).
      2. Post remaining capacity as passive bid at best_ask - 1 (tight queue,
         fills on next bot refresh). If insider signal detected, cross to best_ask.
    """

    def run(self, state: TradingState, td: dict) -> list[Order]:
        self._reset()
        depth = state.order_depths.get(self.symbol)
        if not depth:
            return []

        buy_cap = self.buy_capacity(state)
        if buy_cap <= 0:
            return []

        # -- 1. Take all available asks aggressively ---------------------
        for ask in sorted(depth.sell_orders):
            if buy_cap <= 0:
                break
            vol = min(self.ask_volume(depth, ask), buy_cap)
            self._buy(ask, vol)
            buy_cap -= vol

        # -- 2. Passive bid just below best ask --------------------------
        # best_ask - 1 fills faster than best_bid + 1 when bot refreshes asks.
        # With insider buying, cross the spread immediately (best_ask).
        if buy_cap > 0:
            ba = self.best_ask(depth)
            bb = self.best_bid(depth)
            insider = self.insider_direction(state, self.symbol)
            if ba is not None:
                post_bid = ba if insider > 0 else ba - 1
            elif bb is not None:
                post_bid = bb + 1
            else:
                post_bid = None
            if post_bid is not None:
                self._buy(post_bid, buy_cap)

        if DEBUG:
            pos = self.pos(state)
            print(f"[INTARIAN_PEPPER_ROOT] pos={pos} buy_cap_remaining={buy_cap}")

        return self._orders

# ────────────────────────────────────────────────────────────────────────
# src/trader.py
# ────────────────────────────────────────────────────────────────────────
class Trader:
    """
    Exchange entry point — called once per tick.

    Design principles:
      - traderData is parsed ONCE here into a dict `td`.
      - `td` is passed by reference to every sub-trader's run(state, td).
        Sub-traders read and write directly into `td`; no monkey-patching.
      - After all sub-traders finish, `td` is re-serialised to compact JSON
        and returned as the new traderData string.
      - Conversions are returned as 0 (updated when conversion products arrive).
      - DEBUG = False eliminates all print() calls in competition submissions.
    """

    def __init__(self) -> None:
        self._ash = AshCoatedOsmiumTrader("ASH_COATED_OSMIUM", LIMITS.get("ASH_COATED_OSMIUM", 30))
        self._intarian = IntarianPepperRootTrader("INTARIAN_PEPPER_ROOT", LIMITS.get("INTARIAN_PEPPER_ROOT", 25))

    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        # ── Parse persistent state ───────────────────────────────────────
        td: dict = {}
        if state.traderData:
            try:
                td = json.loads(state.traderData)
            except Exception:
                pass

        # ── Run all sub-traders (td passed by reference) ─────────────────
        orders: dict[str, list[Order]] = {}

        if "ASH_COATED_OSMIUM" in state.order_depths:
            result = self._ash.run(state, td)
            if result:
                orders["ASH_COATED_OSMIUM"] = result

        if "INTARIAN_PEPPER_ROOT" in state.order_depths:
            result = self._intarian.run(state, td)
            if result:
                orders["INTARIAN_PEPPER_ROOT"] = result

        # ── Re-serialise state (compact JSON, minimal bytes) ─────────────
        trader_data = json.dumps(td, separators=(",", ":"))

        return orders, 0, trader_data