# =============================================================================
# solution.py — Auto-generated by build.py. DO NOT EDIT DIRECTLY.
# =============================================================================
from __future__ import annotations
from datamodel import (
    ConversionObservation, Listing, Observation, Order, OrderDepth,
    ProsperityEncoder, Product, Symbol, Trade, TradingState,
)

from collections import deque
import json



# ────────────────────────────────────────────────────────────────────────
# src/config.py
# ────────────────────────────────────────────────────────────────────────
# ============================================================
# GLOBAL CONFIG
# ============================================================

DEBUG = False  # NEVER set True in competition submissions — causes Lambda timeouts

# Position limits per product (updated each round)
LIMITS: dict[str, int] = {
    "EMERALDS": 80,
    "TOMATOES": 80,
    # Round 1 — inferred from max order-book volume (bots post up to their cap)
    "ASH_COATED_OSMIUM": 30,
    "INTARIAN_PEPPER_ROOT": 25,
}

# Master switch: "aggressive" = wide market making, take spreads freely
#                "conservative" = only take near-certain arb, tight sizing
# Can be overridden per-product based on realised volatility regime.
MASTER_SWITCH: str = "aggressive"

# ────────────────────────────────────────────────────────────────────────
# src/base.py
# ────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────────
# Rolling statistics — pure Python, no pandas dependency
# ──────────────────────────────────────────────────────────────────────────────

class RollingWindow:
    """
    Fixed-length rolling window with O(1) append and O(n) mean/std.

    Used for z-score-based pair trading and basket arbitrage.
    State is serialised as a plain list so it can be stored in traderData JSON.

    Lesson from nicolassinott: they used pandas Series with a 200-period window
    and a 5-period short-term smoother. We replicate this in pure Python.
    """

    def __init__(self, maxlen: int) -> None:
        self._maxlen = maxlen
        self._data: deque[float] = deque(maxlen=maxlen)

    # ── Serialisation ──────────────────────────────────────────────────────

    def to_list(self) -> list[float]:
        return list(self._data)

    @classmethod
    def from_list(cls, data: list[float], maxlen: int) -> "RollingWindow":
        w = cls(maxlen)
        w._data = deque(data[-maxlen:], maxlen=maxlen)
        return w

    # ── Mutations ──────────────────────────────────────────────────────────

    def push(self, value: float) -> None:
        self._data.append(value)

    # ── Queries ────────────────────────────────────────────────────────────

    def __len__(self) -> int:
        return len(self._data)

    def is_ready(self) -> bool:
        return len(self._data) == self._maxlen

    def mean(self) -> float:
        n = len(self._data)
        if n == 0:
            return 0.0
        return sum(self._data) / n

    def short_mean(self, n: int = 5) -> float:
        """Mean of the most recent n values (short-term smoother, like nicolassinott's spread_5)."""
        tail = list(self._data)[-n:]
        if not tail:
            return 0.0
        return sum(tail) / len(tail)

    def std(self) -> float:
        n = len(self._data)
        if n < 2:
            return 0.0
        m = self.mean()
        return (sum((x - m) ** 2 for x in self._data) / (n - 1)) ** 0.5

    def zscore(self, short_n: int = 5) -> float | None:
        """
        Z-score of the short-term mean relative to the long-term mean/std.
        Returns None until the window is populated.
        """
        if len(self._data) < max(short_n + 1, 20):
            return None
        s = self.std()
        if s == 0.0:
            return None
        return (self.short_mean(short_n) - self.mean()) / s


# ──────────────────────────────────────────────────────────────────────────────
# Base product trader
# ──────────────────────────────────────────────────────────────────────────────

class BaseProductTrader:
    """
    Shared utilities for all per-product traders.

    Interface:
      run(state, td) -> list[Order]
        state : current TradingState
        td    : already-parsed traderData dict (read + write; changes are
                persisted by Trader.run() after all sub-traders finish)

    Quantities: positive = buy, negative = sell.
    """

    def __init__(self, symbol: str, limit: int) -> None:
        self.symbol = symbol
        self.limit = limit
        self._orders: list[Order] = []

    # ── Internal helpers ───────────────────────────────────────────────────

    def _reset(self) -> None:
        self._orders = []

    def _buy(self, price: int, qty: int) -> None:
        if qty > 0:
            self._orders.append(Order(self.symbol, int(price), int(qty)))

    def _sell(self, price: int, qty: int) -> None:
        if qty > 0:
            self._orders.append(Order(self.symbol, int(price), -int(qty)))

    # ── Position helpers ───────────────────────────────────────────────────

    def pos(self, state: TradingState) -> int:
        return state.position.get(self.symbol, 0)

    def buy_capacity(self, state: TradingState) -> int:
        return self.limit - self.pos(state)

    def sell_capacity(self, state: TradingState) -> int:
        return self.limit + self.pos(state)

    # ── Order-book helpers ─────────────────────────────────────────────────

    @staticmethod
    def best_bid(depth: OrderDepth) -> int | None:
        return max(depth.buy_orders) if depth.buy_orders else None

    @staticmethod
    def best_ask(depth: OrderDepth) -> int | None:
        return min(depth.sell_orders) if depth.sell_orders else None

    @staticmethod
    def bid_volume(depth: OrderDepth, price: int) -> int:
        return depth.buy_orders.get(price, 0)

    @staticmethod
    def ask_volume(depth: OrderDepth, price: int) -> int:
        return abs(depth.sell_orders.get(price, 0))

    @staticmethod
    def vwap_mid(depth: OrderDepth) -> float | None:
        """Volume-weighted mid using best bid and best ask."""
        bb = max(depth.buy_orders) if depth.buy_orders else None
        ba = min(depth.sell_orders) if depth.sell_orders else None
        if bb is None or ba is None:
            return float(bb or ba or 0) or None
        bv = depth.buy_orders[bb]
        av = abs(depth.sell_orders[ba])
        total = bv + av
        if total == 0:
            return (bb + ba) / 2.0
        return (bb * av + ba * bv) / total

    @staticmethod
    def mid(depth: OrderDepth) -> float | None:
        bb = max(depth.buy_orders) if depth.buy_orders else None
        ba = min(depth.sell_orders) if depth.sell_orders else None
        if bb is not None and ba is not None:
            return (bb + ba) / 2.0
        return float(bb or ba or 0) or None

    # ── Insider signal helpers ─────────────────────────────────────────────

    # Key insight from both Alpha Animals and Frankfurt Hedgehogs (P3 winners):
    # a named bot "Olivia" consistently traded at daily extremes, providing a
    # direction signal. We track any known insider name rather than hard-coding
    # one, so the framework generalises to new rounds.
    INSIDER_NAMES: frozenset[str] = frozenset({"Olivia", "Caesar", "Vladimir", "Camilla"})

    @classmethod
    def insider_direction(cls, state: TradingState, symbol: str) -> int:
        """
        +1 if an insider net-bought this tick, -1 if net-sold, 0 otherwise.
        """
        trades = state.market_trades.get(symbol, [])
        bought = sum(t.quantity for t in trades if t.buyer in cls.INSIDER_NAMES)
        sold = sum(t.quantity for t in trades if t.seller in cls.INSIDER_NAMES)
        if bought > sold:
            return 1
        if sold > bought:
            return -1
        return 0

    # ── Wash-trade guard ───────────────────────────────────────────────────

    def _no_wash_trades(self, orders: list[Order]) -> list[Order]:
        """
        Remove any buy order whose price ≥ a sell order's price in the same
        list. Such pairs would self-fill ('wash trade') — disqualifying under
        IMC rules.
        """
        buys = [(i, o) for i, o in enumerate(orders) if o.quantity > 0]
        sells = [(i, o) for i, o in enumerate(orders) if o.quantity < 0]
        bad_indices: set[int] = set()
        for bi, bo in buys:
            for si, so in sells:
                if bo.price >= so.price:
                    bad_indices.add(bi)
                    bad_indices.add(si)
        return [o for i, o in enumerate(orders) if i not in bad_indices]

    # ── Main interface ─────────────────────────────────────────────────────

    def run(self, state: TradingState, td: dict) -> list[Order]:
        raise NotImplementedError

# ────────────────────────────────────────────────────────────────────────
# src/products/ash_coated_osmium.py
# ────────────────────────────────────────────────────────────────────────
class AshCoatedOsmiumTrader(BaseProductTrader):
    """
    Market maker for ASH_COATED_OSMIUM — a fixed fair-value product.

    Data observations (Round 1, 3 days):
      - Fair value is permanently ~10 000 (mean 9998-10001, std ~2).
      - Exchange bots post standing walls at mid +/- 8 ticks (dominant pattern:
        3489 / 3000-tick sample). Occasional outer walls at +/- 9.5-12.
      - Position limit confirmed from order-book max volume: 30.

    Strategy (mirrors EmeraldsTrader, adapted for +-8 bot walls):
      1. TAKE aggressively: buy every ask < FV; sell every bid > FV.
         At exactly FV, only trade to flatten existing inventory.
      2. POST passively:
         - Overbid the standing bot-bid by 1 tick, capped at FV-1.
         - Underask the standing bot-ask by 1 tick, floored at FV+1.
      3. INVENTORY SKEW: position skew bounded to MAX_SPREAD so quotes
         never cross fair value.
    """

    FAIR_VALUE: int = 10_000
    MAX_SPREAD: int = 8      # Bot walls at mid+-8; quote range [FV-8, FV-1] / [FV+1, FV+8]
    SKEW_DIVISOR: float = 4  # Larger -> gentler skew

    def run(self, state: TradingState, td: dict) -> list[Order]:
        self._reset()
        depth = state.order_depths.get(self.symbol)
        if not depth:
            return []

        fv = self.FAIR_VALUE
        pos = self.pos(state)
        buy_cap = self.buy_capacity(state)
        sell_cap = self.sell_capacity(state)

        # -- 1. Aggressive takes -----------------------------------------
        for ask in sorted(depth.sell_orders):
            if buy_cap <= 0:
                break
            if ask < fv:
                vol = min(self.ask_volume(depth, ask), buy_cap)
                self._buy(ask, vol)
                buy_cap -= vol
            elif ask == fv and pos < 0:
                vol = min(self.ask_volume(depth, ask), buy_cap, -pos)
                self._buy(ask, vol)
                buy_cap -= vol

        for bid in sorted(depth.buy_orders, reverse=True):
            if sell_cap <= 0:
                break
            if bid > fv:
                vol = min(self.bid_volume(depth, bid), sell_cap)
                self._sell(bid, vol)
                sell_cap -= vol
            elif bid == fv and pos > 0:
                vol = min(self.bid_volume(depth, bid), sell_cap, pos)
                self._sell(bid, vol)
                sell_cap -= vol

        # -- 2. Passive quotes with inventory skew -----------------------
        skew = round(pos / self.SKEW_DIVISOR / self.limit * self.MAX_SPREAD)

        bb = self.best_bid(depth)
        raw_bid = (bb + 1) if bb is not None else (fv - self.MAX_SPREAD)
        post_bid = max(fv - self.MAX_SPREAD, min(fv - 1, raw_bid)) - skew

        ba = self.best_ask(depth)
        raw_ask = (ba - 1) if ba is not None else (fv + self.MAX_SPREAD)
        post_ask = min(fv + self.MAX_SPREAD, max(fv + 1, raw_ask)) - skew

        if buy_cap > 0 and post_bid < fv:
            self._buy(post_bid, buy_cap)

        if sell_cap > 0 and post_ask > fv:
            self._sell(post_ask, sell_cap)

        orders = self._no_wash_trades(self._orders)

        if DEBUG:
            print(
                f"[ASH_COATED_OSMIUM] pos={pos} skew={skew} "
                f"bid={post_bid} ask={post_ask} "
                f"buy_cap={buy_cap} sell_cap={sell_cap}"
            )

        return orders

# ────────────────────────────────────────────────────────────────────────
# src/products/intarian_pepper_root.py
# ────────────────────────────────────────────────────────────────────────
class IntarianPepperRootTrader(BaseProductTrader):
    """
    Trend follower for INTARIAN_PEPPER_ROOT.

    Data observations (Round 1, 3 days):
      - Price rises at exactly +1.0 per 1000 timestamps, perfectly linear.
      - Day -2: 9998 -> 11002  (+1003 over 999,900 timestamps)
      - Day -1: 10998 -> 11998 (+1000)
      - Day  0: 11998 -> 13000 (+1002)
      - Residual std ~2 ticks (almost no noise around the trend).
      - Position limit confirmed: 25 (max order-book volume, never exceeded).

    Strategy:
      - Hold maximum long position (25 units) at all times.
      - Estimated PnL: 25 x 1000 ticks/day = ~25,000 per day.
      - Never sell: no mean-reversion, no inventory unload.

    Execution:
      1. Take all available asks up to buy capacity.
      2. Post remaining buy capacity as a passive bid at best_ask - 1
         (one tick below best ask to queue priority without crossing spread).
      3. If no ask visible, post at best_bid + 1.
    """

    def run(self, state: TradingState, td: dict) -> list[Order]:
        self._reset()
        depth = state.order_depths.get(self.symbol)
        if not depth:
            return []

        buy_cap = self.buy_capacity(state)
        if buy_cap <= 0:
            return []  # Already at max position, hold

        # -- 1. Take available asks aggressively -------------------------
        for ask in sorted(depth.sell_orders):
            if buy_cap <= 0:
                break
            vol = min(self.ask_volume(depth, ask), buy_cap)
            self._buy(ask, vol)
            buy_cap -= vol

        # -- 2. Post remaining buy capacity as passive bid ---------------
        if buy_cap > 0:
            ba = self.best_ask(depth)
            bb = self.best_bid(depth)
            if ba is not None:
                post_bid = ba - 1
            elif bb is not None:
                post_bid = bb + 1
            else:
                post_bid = None

            if post_bid is not None:
                self._buy(post_bid, buy_cap)

        if DEBUG:
            pos = self.pos(state)
            print(f"[INTARIAN_PEPPER_ROOT] pos={pos} buy_cap_remaining={buy_cap}")

        return self._orders

# ────────────────────────────────────────────────────────────────────────
# src/trader.py
# ────────────────────────────────────────────────────────────────────────
class Trader:
    """
    Exchange entry point — called once per tick.

    Design principles:
      - traderData is parsed ONCE here into a dict `td`.
      - `td` is passed by reference to every sub-trader's run(state, td).
        Sub-traders read and write directly into `td`; no monkey-patching.
      - After all sub-traders finish, `td` is re-serialised to compact JSON
        and returned as the new traderData string.
      - Conversions are returned as 0 (updated when conversion products arrive).
      - DEBUG = False eliminates all print() calls in competition submissions.
    """

    def __init__(self) -> None:
        self._ash = AshCoatedOsmiumTrader("ASH_COATED_OSMIUM", LIMITS.get("ASH_COATED_OSMIUM", 30))
        self._intarian = IntarianPepperRootTrader("INTARIAN_PEPPER_ROOT", LIMITS.get("INTARIAN_PEPPER_ROOT", 25))

    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        # ── Parse persistent state ───────────────────────────────────────
        td: dict = {}
        if state.traderData:
            try:
                td = json.loads(state.traderData)
            except Exception:
                pass

        # ── Run all sub-traders (td passed by reference) ─────────────────
        orders: dict[str, list[Order]] = {}

        if "ASH_COATED_OSMIUM" in state.order_depths:
            result = self._ash.run(state, td)
            if result:
                orders["ASH_COATED_OSMIUM"] = result

        if "INTARIAN_PEPPER_ROOT" in state.order_depths:
            result = self._intarian.run(state, td)
            if result:
                orders["INTARIAN_PEPPER_ROOT"] = result

        # ── Re-serialise state (compact JSON, minimal bytes) ─────────────
        trader_data = json.dumps(td, separators=(",", ":"))

        return orders, 0, trader_data

