# =============================================================================
# solution.py — Auto-generated by build.py. DO NOT EDIT DIRECTLY.
# =============================================================================
from __future__ import annotations
from datamodel import (
    ConversionObservation, Listing, Observation, Order, OrderDepth,
    ProsperityEncoder, Product, Symbol, Trade, TradingState,
)

from collections import deque
import math
import json



# ────────────────────────────────────────────────────────────────────────
# src/config.py
# ────────────────────────────────────────────────────────────────────────
# ============================================================
# GLOBAL CONFIG
# ============================================================

DEBUG = False  # NEVER set True in competition submissions — causes Lambda timeouts

# Position limits per product (updated each round)
LIMITS: dict[str, int] = {
    "EMERALDS": 80,
    "TOMATOES": 80,
}

# Master switch: "aggressive" = wide market making, take spreads freely
#                "conservative" = only take near-certain arb, tight sizing
# Can be overridden per-product based on realised volatility regime.
MASTER_SWITCH: str = "aggressive"

# ────────────────────────────────────────────────────────────────────────
# src/base.py
# ────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────────
# Rolling statistics — pure Python, no pandas dependency
# ──────────────────────────────────────────────────────────────────────────────

class RollingWindow:
    """
    Fixed-length rolling window with O(1) append and O(n) mean/std.

    Used for z-score-based pair trading and basket arbitrage.
    State is serialised as a plain list so it can be stored in traderData JSON.

    Lesson from nicolassinott: they used pandas Series with a 200-period window
    and a 5-period short-term smoother. We replicate this in pure Python.
    """

    def __init__(self, maxlen: int) -> None:
        self._maxlen = maxlen
        self._data: deque[float] = deque(maxlen=maxlen)

    # ── Serialisation ──────────────────────────────────────────────────────

    def to_list(self) -> list[float]:
        return list(self._data)

    @classmethod
    def from_list(cls, data: list[float], maxlen: int) -> "RollingWindow":
        w = cls(maxlen)
        w._data = deque(data[-maxlen:], maxlen=maxlen)
        return w

    # ── Mutations ──────────────────────────────────────────────────────────

    def push(self, value: float) -> None:
        self._data.append(value)

    # ── Queries ────────────────────────────────────────────────────────────

    def __len__(self) -> int:
        return len(self._data)

    def is_ready(self) -> bool:
        return len(self._data) == self._maxlen

    def mean(self) -> float:
        n = len(self._data)
        if n == 0:
            return 0.0
        return sum(self._data) / n

    def short_mean(self, n: int = 5) -> float:
        """Mean of the most recent n values (short-term smoother, like nicolassinott's spread_5)."""
        tail = list(self._data)[-n:]
        if not tail:
            return 0.0
        return sum(tail) / len(tail)

    def std(self) -> float:
        n = len(self._data)
        if n < 2:
            return 0.0
        m = self.mean()
        return (sum((x - m) ** 2 for x in self._data) / (n - 1)) ** 0.5

    def zscore(self, short_n: int = 5) -> float | None:
        """
        Z-score of the short-term mean relative to the long-term mean/std.
        Returns None until the window is populated.
        """
        if len(self._data) < max(short_n + 1, 20):
            return None
        s = self.std()
        if s == 0.0:
            return None
        return (self.short_mean(short_n) - self.mean()) / s


# ──────────────────────────────────────────────────────────────────────────────
# Base product trader
# ──────────────────────────────────────────────────────────────────────────────

class BaseProductTrader:
    """
    Shared utilities for all per-product traders.

    Interface:
      run(state, td) -> list[Order]
        state : current TradingState
        td    : already-parsed traderData dict (read + write; changes are
                persisted by Trader.run() after all sub-traders finish)

    Quantities: positive = buy, negative = sell.
    """

    def __init__(self, symbol: str, limit: int) -> None:
        self.symbol = symbol
        self.limit = limit
        self._orders: list[Order] = []

    # ── Internal helpers ───────────────────────────────────────────────────

    def _reset(self) -> None:
        self._orders = []

    def _buy(self, price: int, qty: int) -> None:
        if qty > 0:
            self._orders.append(Order(self.symbol, int(price), int(qty)))

    def _sell(self, price: int, qty: int) -> None:
        if qty > 0:
            self._orders.append(Order(self.symbol, int(price), -int(qty)))

    # ── Position helpers ───────────────────────────────────────────────────

    def pos(self, state: TradingState) -> int:
        return state.position.get(self.symbol, 0)

    def buy_capacity(self, state: TradingState) -> int:
        return self.limit - self.pos(state)

    def sell_capacity(self, state: TradingState) -> int:
        return self.limit + self.pos(state)

    # ── Order-book helpers ─────────────────────────────────────────────────

    @staticmethod
    def best_bid(depth: OrderDepth) -> int | None:
        return max(depth.buy_orders) if depth.buy_orders else None

    @staticmethod
    def best_ask(depth: OrderDepth) -> int | None:
        return min(depth.sell_orders) if depth.sell_orders else None

    @staticmethod
    def bid_volume(depth: OrderDepth, price: int) -> int:
        return depth.buy_orders.get(price, 0)

    @staticmethod
    def ask_volume(depth: OrderDepth, price: int) -> int:
        return abs(depth.sell_orders.get(price, 0))

    @staticmethod
    def vwap_mid(depth: OrderDepth) -> float | None:
        """Volume-weighted mid using best bid and best ask."""
        bb = max(depth.buy_orders) if depth.buy_orders else None
        ba = min(depth.sell_orders) if depth.sell_orders else None
        if bb is None or ba is None:
            return float(bb or ba or 0) or None
        bv = depth.buy_orders[bb]
        av = abs(depth.sell_orders[ba])
        total = bv + av
        if total == 0:
            return (bb + ba) / 2.0
        return (bb * av + ba * bv) / total

    @staticmethod
    def mid(depth: OrderDepth) -> float | None:
        bb = max(depth.buy_orders) if depth.buy_orders else None
        ba = min(depth.sell_orders) if depth.sell_orders else None
        if bb is not None and ba is not None:
            return (bb + ba) / 2.0
        return float(bb or ba or 0) or None

    # ── Insider signal helpers ─────────────────────────────────────────────

    # Key insight from both Alpha Animals and Frankfurt Hedgehogs (P3 winners):
    # a named bot "Olivia" consistently traded at daily extremes, providing a
    # direction signal. We track any known insider name rather than hard-coding
    # one, so the framework generalises to new rounds.
    INSIDER_NAMES: frozenset[str] = frozenset({"Olivia", "Caesar", "Vladimir", "Camilla"})

    @classmethod
    def insider_direction(cls, state: TradingState, symbol: str) -> int:
        """
        +1 if an insider net-bought this tick, -1 if net-sold, 0 otherwise.
        """
        trades = state.market_trades.get(symbol, [])
        bought = sum(t.quantity for t in trades if t.buyer in cls.INSIDER_NAMES)
        sold = sum(t.quantity for t in trades if t.seller in cls.INSIDER_NAMES)
        if bought > sold:
            return 1
        if sold > bought:
            return -1
        return 0

    # ── Wash-trade guard ───────────────────────────────────────────────────

    def _no_wash_trades(self, orders: list[Order]) -> list[Order]:
        """
        Remove any buy order whose price ≥ a sell order's price in the same
        list. Such pairs would self-fill ('wash trade') — disqualifying under
        IMC rules.
        """
        buys = [(i, o) for i, o in enumerate(orders) if o.quantity > 0]
        sells = [(i, o) for i, o in enumerate(orders) if o.quantity < 0]
        bad_indices: set[int] = set()
        for bi, bo in buys:
            for si, so in sells:
                if bo.price >= so.price:
                    bad_indices.add(bi)
                    bad_indices.add(si)
        return [o for i, o in enumerate(orders) if i not in bad_indices]

    # ── Main interface ─────────────────────────────────────────────────────

    def run(self, state: TradingState, td: dict) -> list[Order]:
        raise NotImplementedError

# ────────────────────────────────────────────────────────────────────────
# src/strategies/pair_trading.py
# ────────────────────────────────────────────────────────────────────────
class PairTrader:
    """
    Statistical arbitrage on two correlated products using a z-score signal.

    Derived from nicolassinott's Round 2 (COCONUT/PINA_COLADAS) and Round 4
    (PICNIC_BASKET components) strategies, but generalised:

      spread = price_B - beta * price_A

    where `beta` is the regression coefficient between the two products.

    Entry:  |z-score| > ENTRY_Z   → trade the spread (long cheap / short rich)
    Exit:   |z-score| < EXIT_Z    → close the position

    Nicolassinott used:
      - Window: 200, short smoother: 5, threshold: 1.5σ (coconuts/pinas)
      - Window: 200, short smoother: 5, threshold: 2.0σ (basket components)
    We use the same defaults but expose them as constructor parameters.

    Usage:
      trader = PairTrader(
          sym_a="COCONUTS", limit_a=300,
          sym_b="PINA_COLADAS", limit_b=100,
          beta=1.551,
          entry_z=1.5, exit_z=0.5,
          trade_size_a=2, trade_size_b=1,
          td_key="coconuts_pinas",
      )
      orders = trader.run(state, td)
    """

    def __init__(
        self,
        sym_a: str,
        limit_a: int,
        sym_b: str,
        limit_b: int,
        beta: float,
        entry_z: float = 1.5,
        exit_z: float = 0.5,
        window: int = 200,
        short_n: int = 5,
        trade_size_a: int = 2,
        trade_size_b: int = 1,
        td_key: str = "pair",
    ) -> None:
        self.sym_a = sym_a
        self.limit_a = limit_a
        self.sym_b = sym_b
        self.limit_b = limit_b
        self.beta = beta
        self.entry_z = entry_z
        self.exit_z = exit_z
        self.window = window
        self.short_n = short_n
        self.trade_size_a = trade_size_a
        self.trade_size_b = trade_size_b
        self.td_key = td_key
        self._helper_a = _OrderHelper(sym_a, limit_a)
        self._helper_b = _OrderHelper(sym_b, limit_b)

    def run(self, state: TradingState, td: dict) -> list[Order]:
        # Get mid prices for both legs
        depth_a = state.order_depths.get(self.sym_a)
        depth_b = state.order_depths.get(self.sym_b)
        if not depth_a or not depth_b:
            return []

        mid_a = _mid(depth_a)
        mid_b = _mid(depth_b)
        if mid_a is None or mid_b is None:
            return []

        # Load state
        key = self.td_key
        spread_history: list[float] = td.get(f"{key}_window", [])
        pair_pos: int = td.get(f"{key}_pos", 0)

        roll = RollingWindow.from_list(spread_history, self.window)

        # Update spread window
        spread = mid_b - self.beta * mid_a
        roll.push(spread)
        td[f"{key}_window"] = roll.to_list()

        z = roll.zscore(self.short_n)
        if z is None:
            return []

        orders: list[Order] = []
        pos_a = state.position.get(self.sym_a, 0)
        pos_b = state.position.get(self.sym_b, 0)

        # Long spread: sell A, buy B (spread is too low — B is cheap relative to A)
        if z < -self.entry_z and pair_pos <= 0:
            vol_a = min(self.trade_size_a, self.limit_a + pos_a)  # short A
            vol_b = min(self.trade_size_b, self.limit_b - pos_b)  # long B
            if vol_a > 0 and vol_b > 0:
                ba = BaseProductTrader.best_ask(depth_a)
                bb_b = BaseProductTrader.best_bid(depth_b)
                if ba and bb_b:
                    orders.append(Order(self.sym_a, ba + 1, -vol_a))  # sell A aggressively
                    orders.append(Order(self.sym_b, bb_b + 1, vol_b))  # buy B aggressively
                    td[f"{key}_pos"] = pair_pos - 1

        # Short spread: buy A, sell B (spread is too high — A is cheap relative to B)
        elif z > self.entry_z and pair_pos >= 0:
            vol_a = min(self.trade_size_a, self.limit_a - pos_a)   # long A
            vol_b = min(self.trade_size_b, self.limit_b + pos_b)   # short B
            if vol_a > 0 and vol_b > 0:
                bb_a = BaseProductTrader.best_bid(depth_a)
                ba_b = BaseProductTrader.best_ask(depth_b)
                if bb_a and ba_b:
                    orders.append(Order(self.sym_a, bb_a - 1, vol_a))   # buy A aggressively
                    orders.append(Order(self.sym_b, ba_b - 1, -vol_b))  # sell B aggressively
                    td[f"{key}_pos"] = pair_pos + 1

        # Exit: z-score has reverted
        elif abs(z) < self.exit_z and pair_pos != 0:
            if pair_pos < 0:  # was long spread: unwind (buy A, sell B)
                bb_a = BaseProductTrader.best_bid(depth_a)
                ba_b = BaseProductTrader.best_ask(depth_b)
                if bb_a and ba_b:
                    vol_a = min(self.trade_size_a, self.limit_a - pos_a)
                    vol_b = min(self.trade_size_b, self.limit_b + pos_b)
                    if vol_a > 0 and vol_b > 0:
                        orders.append(Order(self.sym_a, bb_a - 1, vol_a))
                        orders.append(Order(self.sym_b, ba_b - 1, -vol_b))
                        td[f"{key}_pos"] = 0
            else:  # was short spread: unwind (sell A, buy B)
                ba = BaseProductTrader.best_ask(depth_a)
                bb_b = BaseProductTrader.best_bid(depth_b)
                if ba and bb_b:
                    vol_a = min(self.trade_size_a, self.limit_a + pos_a)
                    vol_b = min(self.trade_size_b, self.limit_b - pos_b)
                    if vol_a > 0 and vol_b > 0:
                        orders.append(Order(self.sym_a, ba + 1, -vol_a))
                        orders.append(Order(self.sym_b, bb_b + 1, vol_b))
                        td[f"{key}_pos"] = 0

        if DEBUG:
            print(f"[PAIR {self.sym_a}/{self.sym_b}] z={z:.2f} pair_pos={pair_pos} spread={spread:.2f}")

        return orders


class BasketArb:
    """
    Basket arbitrage: trade a basket instrument vs. its synthetic replication.

    Derived from nicolassinott's Round 4 PICNIC_BASKET strategy:
      spread = price_basket - (w1*price_A + w2*price_B + w3*price_C)
      entry threshold: 2σ, window: 200, short_n: 5

    Usage:
      arb = BasketArb(
          basket_sym="PICNIC_BASKET", basket_limit=70,
          components=[("UKULELE",1,60), ("BAGUETTE",2,120), ("DIP",4,240)],
          entry_z=2.0, exit_z=0.5,
          trade_size=2,
          td_key="basket_arb",
      )
    """

    def __init__(
        self,
        basket_sym: str,
        basket_limit: int,
        components: list[tuple[str, float, int]],   # (symbol, weight, limit)
        entry_z: float = 2.0,
        exit_z: float = 0.5,
        window: int = 200,
        short_n: int = 5,
        trade_size: int = 2,
        td_key: str = "basket",
    ) -> None:
        self.basket_sym = basket_sym
        self.basket_limit = basket_limit
        self.components = components
        self.entry_z = entry_z
        self.exit_z = exit_z
        self.window = window
        self.short_n = short_n
        self.trade_size = trade_size
        self.td_key = td_key

    def _synthetic_price(self, state: TradingState) -> float | None:
        total = 0.0
        for sym, weight, _ in self.components:
            depth = state.order_depths.get(sym)
            if not depth:
                return None
            m = _mid(depth)
            if m is None:
                return None
            total += weight * m
        return total

    def run(self, state: TradingState, td: dict) -> list[Order]:
        basket_depth = state.order_depths.get(self.basket_sym)
        if not basket_depth:
            return []

        basket_mid = _mid(basket_depth)
        synth = self._synthetic_price(state)
        if basket_mid is None or synth is None:
            return []

        key = self.td_key
        history: list[float] = td.get(f"{key}_window", [])
        roll = RollingWindow.from_list(history, self.window)

        spread = basket_mid - synth
        roll.push(spread)
        td[f"{key}_window"] = roll.to_list()

        z = roll.zscore(self.short_n)
        if z is None:
            return []

        orders: list[Order] = []
        basket_pos = state.position.get(self.basket_sym, 0)

        # Basket is CHEAP (spread below mean): buy basket, sell components
        if z < -self.entry_z and abs(basket_pos) <= self.basket_limit - self.trade_size:
            ba = BaseProductTrader.best_ask(basket_depth)
            if ba:
                orders.append(Order(self.basket_sym, ba, self.trade_size))
            for sym, weight, lim in self.components:
                comp_pos = state.position.get(sym, 0)
                comp_depth = state.order_depths.get(sym)
                if comp_depth:
                    cb = BaseProductTrader.best_bid(comp_depth)
                    sell_vol = min(round(weight * self.trade_size), lim + comp_pos)
                    if cb and sell_vol > 0:
                        orders.append(Order(sym, cb, -sell_vol))

        # Basket is EXPENSIVE (spread above mean): sell basket, buy components
        elif z > self.entry_z and abs(basket_pos) <= self.basket_limit - self.trade_size:
            bb = BaseProductTrader.best_bid(basket_depth)
            if bb:
                orders.append(Order(self.basket_sym, bb, -self.trade_size))
            for sym, weight, lim in self.components:
                comp_pos = state.position.get(sym, 0)
                comp_depth = state.order_depths.get(sym)
                if comp_depth:
                    ca = BaseProductTrader.best_ask(comp_depth)
                    buy_vol = min(round(weight * self.trade_size), lim - comp_pos)
                    if ca and buy_vol > 0:
                        orders.append(Order(sym, ca, buy_vol))

        if DEBUG:
            print(f"[BASKET {self.basket_sym}] z={z:.2f} spread={spread:.2f} basket_pos={basket_pos}")

        return orders


# ── Internal helpers ───────────────────────────────────────────────────────────

class _OrderHelper(BaseProductTrader):
    """Thin wrapper used just to access BaseProductTrader statics."""
    def run(self, state, td):
        return []


def _mid(depth) -> float | None:
    bb = max(depth.buy_orders) if depth.buy_orders else None
    ba = min(depth.sell_orders) if depth.sell_orders else None
    if bb is not None and ba is not None:
        return (bb + ba) / 2.0
    return float(bb or ba or 0) or None

# ────────────────────────────────────────────────────────────────────────
# src/strategies/seasonal.py
# ────────────────────────────────────────────────────────────────────────
class SeasonalTrader:
    """
    Timestamp-based seasonal trading for products with predictable price
    patterns within a day (e.g. BERRIES in P2 which peaked mid-day).

    Derived from nicolassinott's Round 3 BERRIES strategy:
      - Buy around timestamp 200 000 (± tolerance)
      - Sell around timestamp 500 000 (± tolerance)

    Enhanced with insider signal override (Olivia pattern from P3):
      If an insider is trading in the same direction as the seasonal signal,
      the position size is increased by INSIDER_BOOST_FACTOR.

    Usage:
      trader = SeasonalTrader(
          symbol="BERRIES",
          limit=250,
          buy_ts=200_000,
          sell_ts=500_000,
          tolerance=800,
          trade_size=40,
          td_key="berries_seasonal",
      )
    """

    INSIDER_BOOST_FACTOR: float = 1.5

    def __init__(
        self,
        symbol: str,
        limit: int,
        buy_ts: int,
        sell_ts: int,
        tolerance: int = 800,
        trade_size: int = 40,
        td_key: str = "seasonal",
    ) -> None:
        self.symbol = symbol
        self.limit = limit
        self.buy_ts = buy_ts
        self.sell_ts = sell_ts
        self.tolerance = tolerance
        self.trade_size = trade_size
        self.td_key = td_key
        self._helper = BaseProductTrader.__new__(BaseProductTrader)
        self._helper.symbol = symbol
        self._helper.limit = limit

    def run(self, state: TradingState, td: dict) -> list[Order]:
        depth = state.order_depths.get(self.symbol)
        if not depth:
            return []

        ts = state.timestamp
        orders: list[Order] = []
        pos = state.position.get(self.symbol, 0)
        insider = BaseProductTrader.insider_direction(state, self.symbol)

        in_buy_window = abs(ts - self.buy_ts) <= self.tolerance
        in_sell_window = abs(ts - self.sell_ts) <= self.tolerance

        if in_buy_window and pos < self.limit:
            size = self.trade_size
            if insider > 0:
                size = min(int(size * self.INSIDER_BOOST_FACTOR), self.limit - pos)
            ba = min(depth.sell_orders) if depth.sell_orders else None
            if ba:
                buy_vol = min(size, self.limit - pos)
                if buy_vol > 0:
                    orders.append(Order(self.symbol, ba, buy_vol))

        elif in_sell_window and pos > -self.limit:
            size = self.trade_size
            if insider < 0:
                size = min(int(size * self.INSIDER_BOOST_FACTOR), self.limit + pos)
            bb = max(depth.buy_orders) if depth.buy_orders else None
            if bb:
                sell_vol = min(size, self.limit + pos)
                if sell_vol > 0:
                    orders.append(Order(self.symbol, bb, -sell_vol))

        if DEBUG:
            print(f"[SEASONAL {self.symbol}] ts={ts} pos={pos} insider={insider} in_buy={in_buy_window} in_sell={in_sell_window}")

        return orders


class DerivativeSignalTrader:
    """
    Trade a product based on percentage changes in an external observation
    (e.g. DOLPHIN_SIGHTINGS predicts DIVING_GEAR in P2/P3).

    Derived from nicolassinott's Round 3 DIVING_GEAR strategy:
      - Long trigger: pct_change_dolphin > +0.002
      - Short trigger: pct_change_dolphin < -0.002
      - Minimum hold: 2000 timestamps
      - Close: 3 consecutive bars moving against position
    """

    def __init__(
        self,
        symbol: str,
        limit: int,
        observation_key: str,           # key in state.observations.plainValueObservations
        long_threshold: float = 0.002,
        short_threshold: float = -0.002,
        min_hold_ts: int = 2000,
        td_key: str = "deriv_signal",
    ) -> None:
        self.symbol = symbol
        self.limit = limit
        self.obs_key = observation_key
        self.long_thr = long_threshold
        self.short_thr = short_threshold
        self.min_hold_ts = min_hold_ts
        self.td_key = td_key

    def run(self, state: TradingState, td: dict) -> list[Order]:
        depth = state.order_depths.get(self.symbol)
        obs_val = state.observations.plainValueObservations.get(self.obs_key)
        if depth is None or obs_val is None:
            return []

        key = self.td_key
        last_obs: float = td.get(f"{key}_last_obs", float(obs_val))
        signal_ts: int = td.get(f"{key}_signal_ts", 0)
        signal_dir: int = td.get(f"{key}_signal_dir", 0)
        consec_against: int = td.get(f"{key}_consec", 0)

        pct_change = (float(obs_val) - last_obs) / max(abs(last_obs), 1e-6)

        # Detect new signal
        new_dir = 0
        if pct_change > self.long_thr:
            new_dir = 1
        elif pct_change < self.short_thr:
            new_dir = -1

        if new_dir != 0 and signal_dir == 0:
            signal_dir = new_dir
            signal_ts = state.timestamp
            consec_against = 0

        # Track consecutive adverse returns for exit
        if signal_dir != 0:
            if (signal_dir > 0 and pct_change < 0) or (signal_dir < 0 and pct_change > 0):
                consec_against += 1
            else:
                consec_against = 0

        td[f"{key}_last_obs"] = float(obs_val)
        td[f"{key}_signal_ts"] = signal_ts
        td[f"{key}_signal_dir"] = signal_dir
        td[f"{key}_consec"] = consec_against

        orders: list[Order] = []
        pos = state.position.get(self.symbol, 0)
        held_long_enough = (state.timestamp - signal_ts) >= self.min_hold_ts
        should_close = held_long_enough and consec_against >= 3

        bb = max(depth.buy_orders) if depth.buy_orders else None
        ba = min(depth.sell_orders) if depth.sell_orders else None

        if should_close and pos != 0:
            # Close position: place aggressive order 200 ticks away to ensure fill
            if pos > 0 and bb:
                orders.append(Order(self.symbol, bb - 200, -pos))
            elif pos < 0 and ba:
                orders.append(Order(self.symbol, ba + 200, -pos))
            td[f"{key}_signal_dir"] = 0

        elif signal_dir > 0 and pos < self.limit and not should_close:
            if ba:
                vol = min(self.limit - pos, self.limit)
                orders.append(Order(self.symbol, ba + 200, vol))

        elif signal_dir < 0 and pos > -self.limit and not should_close:
            if bb:
                vol = min(self.limit + pos, self.limit)
                orders.append(Order(self.symbol, bb - 200, -vol))

        if DEBUG:
            print(f"[DERIV {self.symbol}] dir={signal_dir} consec={consec_against} pos={pos} pct={pct_change:.4f}")

        return orders

# ────────────────────────────────────────────────────────────────────────
# src/products/emeralds.py
# ────────────────────────────────────────────────────────────────────────
class EmeraldsTrader(BaseProductTrader):
    """
    Market maker for EMERALDS — a fixed fair-value product.

    Data observations (tutorial round):
      - Fair value is permanently 10 000.
      - Exchange bots post standing walls: bid at 9 992 (vol ~10-15),
        ask at 10 008 (vol ~10-15).
      - Occasional mid-book orders appear at exactly 10 000.

    Strategy (derived from Frankfurt Hedgehogs + Alpha Animals P3 approach):
      1. TAKE aggressively: buy every ask < FV; sell every bid > FV.
         At exactly FV, only trade to flatten existing inventory.
      2. POST passively:
         - Overbid the standing bot-bid by 1 tick (e.g. 9993 vs 9992),
           capped at FV-1. This captures any market sell order that would
           otherwise fill the bot's 9992 bid.
         - Underask the standing bot-ask by 1 tick (e.g. 10007 vs 10008),
           floored at FV+1.
      3. INVENTORY SKEW: if position > 0, shift both quotes downward to
         encourage position mean-reversion. Skew is bounded to MAX_SPREAD
         so quotes never cross the fair value.

    Lesson from nicolassinott (91st, P1):
      Their Pearls strategy posted at FV±1 only. Our approach is strictly
      superior because we overbid/underask the bot walls, gaining queue
      priority over them while staying inside the profitable range.
    """

    FAIR_VALUE: int = 10_000
    MAX_SPREAD: int = 7      # Quote range: [FV-7, FV-1] bid, [FV+1, FV+7] ask
    SKEW_DIVISOR: float = 4  # Larger → gentler skew

    def run(self, state: TradingState, td: dict) -> list[Order]:
        self._reset()
        depth = state.order_depths.get(self.symbol)
        if not depth:
            return []

        fv = self.FAIR_VALUE
        pos = self.pos(state)
        buy_cap = self.buy_capacity(state)
        sell_cap = self.sell_capacity(state)

        # ── 1. Aggressive takes ──────────────────────────────────────────
        for ask in sorted(depth.sell_orders):
            if buy_cap <= 0:
                break
            if ask < fv:
                vol = min(self.ask_volume(depth, ask), buy_cap)
                self._buy(ask, vol)
                buy_cap -= vol
            elif ask == fv and pos < 0:
                vol = min(self.ask_volume(depth, ask), buy_cap, -pos)
                self._buy(ask, vol)
                buy_cap -= vol

        for bid in sorted(depth.buy_orders, reverse=True):
            if sell_cap <= 0:
                break
            if bid > fv:
                vol = min(self.bid_volume(depth, bid), sell_cap)
                self._sell(bid, vol)
                sell_cap -= vol
            elif bid == fv and pos > 0:
                vol = min(self.bid_volume(depth, bid), sell_cap, pos)
                self._sell(bid, vol)
                sell_cap -= vol

        # ── 2. Passive quotes with inventory skew ───────────────────────
        skew = round(pos / self.SKEW_DIVISOR / self.limit * self.MAX_SPREAD)

        bb = self.best_bid(depth)
        raw_bid = (bb + 1) if bb is not None else (fv - self.MAX_SPREAD)
        post_bid = max(fv - self.MAX_SPREAD, min(fv - 1, raw_bid)) - skew

        ba = self.best_ask(depth)
        raw_ask = (ba - 1) if ba is not None else (fv + self.MAX_SPREAD)
        post_ask = min(fv + self.MAX_SPREAD, max(fv + 1, raw_ask)) - skew

        if buy_cap > 0 and post_bid < fv:
            self._buy(post_bid, buy_cap)

        if sell_cap > 0 and post_ask > fv:
            self._sell(post_ask, sell_cap)

        orders = self._no_wash_trades(self._orders)

        if DEBUG:
            print(
                f"[EMERALDS] pos={pos} skew={skew} "
                f"bid={post_bid} ask={post_ask} "
                f"buy_cap={buy_cap} sell_cap={sell_cap}"
            )

        return orders

# ────────────────────────────────────────────────────────────────────────
# src/products/tomatoes.py
# ────────────────────────────────────────────────────────────────────────
class TomatoesTrader(BaseProductTrader):
    """
    Market maker for TOMATOES — a slow random-walk product.

    Data observations (tutorial round):
      - No fixed fair value; mid-price drifts around ~5 000.
      - Bot walls: bid ~4 999-5 000, ask ~5 013-5 014 (≈13 tick spread).
      - No clear insider signal in tutorial data.

    Strategy:
      1. Estimate fair value via EMA of VWAP mid (smoothed to reduce adverse
         selection on noisy ticks).
      2. TAKE aggressively: only when market price has moved TAKE_EDGE ticks
         away from our EMA (i.e. clear dislocation). This avoids chasing noise.
      3. POST passively with POSITION-CONDITIONAL quoting — adopted from
         nicolassinott's Bananas strategy (91st, P1):
           - Neutral:  bid at floor(fv - BASE_SPREAD), ask at ceil(fv + BASE_SPREAD)
           - Long:     widen bid (don't want more), tighten ask (want to sell)
           - Short:    tighten bid (want to buy),   widen ask  (don't want to sell)
         This is more intuitive and transparent than a continuous skew formula.

    Lesson from nicolassinott:
      They used EMA α=0.5. We use α=0.3 (less reactive) to avoid
      chasing the noisy TOMATOES price. The wider spread (13 ticks) means
      the price has significant noise; a slower EMA is safer.

    State in traderData:
      "tomatoes_ema": float
    """

    EMA_ALPHA: float = 0.3
    BASE_SPREAD: int = 4    # Neutral half-spread
    WIDE_SPREAD: int = 6    # Wide side when holding inventory
    TAKE_EDGE: int = 2      # Take only when ask <= fv-TAKE_EDGE or bid >= fv+TAKE_EDGE

    TD_KEY: str = "tomatoes_ema"

    def run(self, state: TradingState, td: dict) -> list[Order]:
        self._reset()
        depth = state.order_depths.get(self.symbol)
        if not depth:
            return []

        raw_mid = self.vwap_mid(depth)
        if raw_mid is None:
            return []

        # ── Load / update EMA ────────────────────────────────────────────
        ema_fv: float = td.get(self.TD_KEY, raw_mid)
        ema_fv = self.EMA_ALPHA * raw_mid + (1 - self.EMA_ALPHA) * ema_fv
        td[self.TD_KEY] = ema_fv  # write back — caller persists td

        fv = ema_fv
        pos = self.pos(state)
        buy_cap = self.buy_capacity(state)
        sell_cap = self.sell_capacity(state)

        # ── 1. Aggressive takes (dislocation only) ──────────────────────
        for ask in sorted(depth.sell_orders):
            if buy_cap <= 0:
                break
            if ask <= fv - self.TAKE_EDGE:
                vol = min(self.ask_volume(depth, ask), buy_cap)
                self._buy(ask, vol)
                buy_cap -= vol

        for bid in sorted(depth.buy_orders, reverse=True):
            if sell_cap <= 0:
                break
            if bid >= fv + self.TAKE_EDGE:
                vol = min(self.bid_volume(depth, bid), sell_cap)
                self._sell(bid, vol)
                sell_cap -= vol

        # ── 2. Position-conditional passive quotes ───────────────────────
        # Inspired by nicolassinott's Bananas approach:
        #   neutral → symmetric tight quotes
        #   long    → wide bid (reduce buying), tight ask (encourage selling)
        #   short   → tight bid (encourage buying), wide ask (reduce selling)
        if pos == 0:
            bid_spread = self.BASE_SPREAD
            ask_spread = self.BASE_SPREAD
        elif pos > 0:
            bid_spread = self.WIDE_SPREAD
            ask_spread = self.BASE_SPREAD
        else:
            bid_spread = self.BASE_SPREAD
            ask_spread = self.WIDE_SPREAD

        post_bid = math.floor(fv) - bid_spread
        post_ask = math.ceil(fv) + ask_spread

        if buy_cap > 0:
            self._buy(post_bid, buy_cap)

        if sell_cap > 0:
            self._sell(post_ask, sell_cap)

        orders = self._no_wash_trades(self._orders)

        if DEBUG:
            print(
                f"[TOMATOES] pos={pos} ema={fv:.2f} raw={raw_mid:.2f} "
                f"bid={post_bid}(-{bid_spread}) ask={post_ask}(+{ask_spread}) "
                f"buy_cap={buy_cap} sell_cap={sell_cap}"
            )

        return orders

# ────────────────────────────────────────────────────────────────────────
# src/trader.py
# ────────────────────────────────────────────────────────────────────────
class Trader:
    """
    Exchange entry point — called once per tick.

    Design principles:
      - traderData is parsed ONCE here into a dict `td`.
      - `td` is passed by reference to every sub-trader's run(state, td).
        Sub-traders read and write directly into `td`; no monkey-patching.
      - After all sub-traders finish, `td` is re-serialised to compact JSON
        and returned as the new traderData string.
      - Conversions are returned as 0 (updated when conversion products arrive).
      - DEBUG = False eliminates all print() calls in competition submissions.
    """

    def __init__(self) -> None:
        self._emeralds = EmeraldsTrader("EMERALDS", LIMITS.get("EMERALDS", 50))
        self._tomatoes = TomatoesTrader("TOMATOES", LIMITS.get("TOMATOES", 50))
        # Round 2+ traders are added here when round data becomes available:
        # self._coconuts_pinas = PairTrader(...)
        # self._basket = BasketArb(...)
        # self._berries = SeasonalTrader(...)

    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        # ── Parse persistent state ───────────────────────────────────────
        td: dict = {}
        if state.traderData:
            try:
                td = json.loads(state.traderData)
            except Exception:
                pass

        # ── Run all sub-traders (td passed by reference) ─────────────────
        orders: dict[str, list[Order]] = {}

        if "EMERALDS" in state.order_depths:
            result = self._emeralds.run(state, td)
            if result:
                orders["EMERALDS"] = result

        if "TOMATOES" in state.order_depths:
            result = self._tomatoes.run(state, td)
            if result:
                orders["TOMATOES"] = result

        # Round 2+: uncomment when products become available
        # if "COCONUTS" in state.order_depths and "PINA_COLADAS" in state.order_depths:
        #     for o in self._coconuts_pinas.run(state, td):
        #         orders.setdefault(o.symbol, []).append(o)
        #
        # if "PICNIC_BASKET" in state.order_depths:
        #     for o in self._basket.run(state, td):
        #         orders.setdefault(o.symbol, []).append(o)

        # ── Re-serialise state (compact JSON, minimal bytes) ─────────────
        trader_data = json.dumps(td, separators=(",", ":"))

        return orders, 0, trader_data

